[package]
name = "mew-ext-broker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
ulid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
http = "1"
sha2 = "0.10"
directories = { workspace = true }
mew-hooks = { workspace = true }
mew-hooks-runtime = { workspace = true }
mew-message = { workspace = true }
mew-provider = { workspace = true }

[dev-dependencies]
tempfile = "3"
