[package]
name = "mew-provider"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mew-message = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
http = "1"
tokio = { workspace = true }
anyhow = { workspace = true }
base64 = "0.22"
tracing = { workspace = true }
