[package]
name = "mew"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "mew"
path = "src/main.rs"

[dependencies]
mew-message = { workspace = true }
mew-provider = { workspace = true }
mew-provider-openai = { workspace = true }
mew-provider-anthropic = { workspace = true }
mew-provider-fake = { workspace = true }
mew-agent = { workspace = true }
mew-tools = { workspace = true }
mew-config = { workspace = true }
mew-session = { workspace = true }
mew-catalog = { workspace = true }
mew-context = { workspace = true }
mew-skills = { workspace = true }
mew-hooks = { workspace = true }
mew-tui = { workspace = true }
mew-mcp = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
chrono = { workspace = true }

tokio = { workspace = true }
ulid = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
